server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap}
  application:
    name: observability-producer-service

app:
  kafka:
    bootstrap: PLAINTEXT://localhost:9090
    topic: topic-observability
  outbound:
    rest-clients:
      bridge:
        base-url: http://localhost:8084
